//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazingCoffee.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazingCoffee.Shared.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazing Coffee Warehouse.
        /// </summary>
        public static string Blazing_Coffee_Title {
            get {
                return ResourceManager.GetString("Blazing_Coffee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Teams.
        /// </summary>
        public static string ButtonGroup_AllTeams {
            get {
                return ResourceManager.GetString("ButtonGroup_AllTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Team.
        /// </summary>
        public static string ButtonGroup_MyTeam {
            get {
                return ResourceManager.GetString("ButtonGroup_MyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend.
        /// </summary>
        public static string ButtonGroup_Trend {
            get {
                return ResourceManager.GetString("ButtonGroup_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string ButtonGroup_Volume {
            get {
                return ResourceManager.GetString("ButtonGroup_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales and Revenue Total.
        /// </summary>
        public static string ChartTitle_SalesAndRevenueTotal {
            get {
                return ResourceManager.GetString("ChartTitle_SalesAndRevenueTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        public static string ChartValueAxisTitle_TotalSales {
            get {
                return ResourceManager.GetString("ChartValueAxisTitle_TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmDialog_AreYouSure {
            get {
                return ResourceManager.GetString("ConfirmDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to the database..
        /// </summary>
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Drawer_Dashboard {
            get {
                return ResourceManager.GetString("Drawer_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Drawer_Info {
            get {
                return ResourceManager.GetString("Drawer_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Drawer_Profile {
            get {
                return ResourceManager.GetString("Drawer_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Drawer_Team {
            get {
                return ResourceManager.GetString("Drawer_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employee_Grid_Title_Address {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Employee_Grid_Title_Budget {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Employee_Grid_Title_Contacts {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Employee_Grid_Title_Country {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement.
        /// </summary>
        public static string Employee_Grid_Title_Engagement {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Employee_Grid_Title_FullName {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Employee_Grid_Title_JobTitle {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Employee_Grid_Title_Performance {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee_Grid_Title_Personal_Information {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Personal_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Employee_Grid_Title_Phone {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Employee_Grid_Title_Rating {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Employee_Grid_Title_Status {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string Employee_Grid_Title_TeamName {
            get {
                return ResourceManager.GetString("Employee_Grid_Title_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Submit Successful!.
        /// </summary>
        public static string Form_Submit_Success {
            get {
                return ResourceManager.GetString("Form_Submit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string Grid_CsvExport {
            get {
                return ResourceManager.GetString("Grid_CsvExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string Grid_ExcelExport {
            get {
                return ResourceManager.GetString("Grid_ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Capital.
        /// </summary>
        public static string HumanCapital {
            get {
                return ResourceManager.GetString("HumanCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage employees and teams..
        /// </summary>
        public static string Index_EmployeesCard_Description {
            get {
                return ResourceManager.GetString("Index_EmployeesCard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage products and nutrition information..
        /// </summary>
        public static string Index_ProductsCard_Description {
            get {
                return ResourceManager.GetString("Index_ProductsCard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report on Sales..
        /// </summary>
        public static string Index_SalesCard_Description {
            get {
                return ResourceManager.GetString("Index_SalesCard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string LanguageChooser_SelectLanguage {
            get {
                return ResourceManager.GetString("LanguageChooser_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string MainLayout_Documentation {
            get {
                return ResourceManager.GetString("MainLayout_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Products.
        /// </summary>
        public static string ManageProducts {
            get {
                return ResourceManager.GetString("ManageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string ManageProducts_AddProduct {
            get {
                return ResourceManager.GetString("ManageProducts_AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete {0} permanently..
        /// </summary>
        public static string ManageProducts_ConfirmDelete {
            get {
                return ResourceManager.GetString("ManageProducts_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product {0} was added..
        /// </summary>
        public static string ManageProducts_Create_Success {
            get {
                return ResourceManager.GetString("ManageProducts_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product {0} was deleted..
        /// </summary>
        public static string ManageProducts_Delete_Success {
            get {
                return ResourceManager.GetString("ManageProducts_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product {0} was updated..
        /// </summary>
        public static string ManageProducts_Update_Success {
            get {
                return ResourceManager.GetString("ManageProducts_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string Nav_MoreInfo {
            get {
                return ResourceManager.GetString("Nav_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition Info.
        /// </summary>
        public static string Nutrition_Info_ {
            get {
                return ResourceManager.GetString("Nutrition Info.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save, then edit to add nutrition info..
        /// </summary>
        public static string Product_Upload_SaveDialog {
            get {
                return ResourceManager.GetString("Product_Upload_SaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Biography.
        /// </summary>
        public static string Profile_Bio {
            get {
                return ResourceManager.GetString("Profile_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Profile_Country {
            get {
                return ResourceManager.GetString("Profile_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Deactivated.
        /// </summary>
        public static string Profile_IsDeleted {
            get {
                return ResourceManager.GetString("Profile_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone .
        /// </summary>
        public static string Profile_Phone {
            get {
                return ResourceManager.GetString("Profile_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Profile_SaveChanges {
            get {
                return ResourceManager.GetString("Profile_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Profile_Team {
            get {
                return ResourceManager.GetString("Profile_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Efficiency.
        /// </summary>
        public static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue for.
        /// </summary>
        public static string Revenue_For {
            get {
                return ResourceManager.GetString("Revenue_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Sales_Grid_Title_Amount {
            get {
                return ResourceManager.GetString("Sales_Grid_Title_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Sales_Grid_Title_Country {
            get {
                return ResourceManager.GetString("Sales_Grid_Title_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Sales_Grid_Title_Region {
            get {
                return ResourceManager.GetString("Sales_Grid_Title_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Sales_Grid_Title_Sku {
            get {
                return ResourceManager.GetString("Sales_Grid_Title_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Sales_Grid_Title_StoreId {
            get {
                return ResourceManager.GetString("Sales_Grid_Title_StoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string Sales_Grid_Title_TransactionDate {
            get {
                return ResourceManager.GetString("Sales_Grid_Title_TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Range:.
        /// </summary>
        public static string Sales_Grid_Toolbar_ReportRange {
            get {
                return ResourceManager.GetString("Sales_Grid_Toolbar_ReportRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Id.
        /// </summary>
        public static string Toggle_Id {
            get {
                return ResourceManager.GetString("Toggle_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login required.
        /// </summary>
        public static string ToolTip_LoginRequired {
            get {
                return ResourceManager.GetString("ToolTip_LoginRequired", resourceCulture);
            }
        }
    }
}
