//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazingCoffee.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelerikMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelerikMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazingCoffee.Shared.Resources.TelerikMessages", typeof(TelerikMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Aggregate_Average {
            get {
                return ResourceManager.GetString("Aggregate_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Aggregate_Count {
            get {
                return ResourceManager.GetString("Aggregate_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Aggregate_Max {
            get {
                return ResourceManager.GetString("Aggregate_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Aggregate_Min {
            get {
                return ResourceManager.GetString("Aggregate_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Aggregate_Sum {
            get {
                return ResourceManager.GetString("Aggregate_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string AutoComplete_Clear {
            get {
                return ResourceManager.GetString("AutoComplete_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string AutoComplete_NoData {
            get {
                return ResourceManager.GetString("AutoComplete_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a decade.
        /// </summary>
        public static string Calendar_Choose_Decade {
            get {
                return ResourceManager.GetString("Calendar_Choose_Decade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a month.
        /// </summary>
        public static string Calendar_Choose_Month {
            get {
                return ResourceManager.GetString("Calendar_Choose_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an year.
        /// </summary>
        public static string Calendar_Choose_Year {
            get {
                return ResourceManager.GetString("Calendar_Choose_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next period.
        /// </summary>
        public static string Calendar_GoToNext {
            get {
                return ResourceManager.GetString("Calendar_GoToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous period.
        /// </summary>
        public static string Calendar_GoToPrevious {
            get {
                return ResourceManager.GetString("Calendar_GoToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Calendar_Today {
            get {
                return ResourceManager.GetString("Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ColumnMenu_Apply {
            get {
                return ResourceManager.GetString("ColumnMenu_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column menu.
        /// </summary>
        public static string ColumnMenu_ColumnMenu {
            get {
                return ResourceManager.GetString("ColumnMenu_ColumnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string ColumnMenu_Columns {
            get {
                return ResourceManager.GetString("ColumnMenu_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group column.
        /// </summary>
        public static string ColumnMenu_GroupColumn {
            get {
                return ResourceManager.GetString("ColumnMenu_GroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string ColumnMenu_Lock {
            get {
                return ResourceManager.GetString("ColumnMenu_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Next.
        /// </summary>
        public static string ColumnMenu_ReorderNext {
            get {
                return ResourceManager.GetString("ColumnMenu_ReorderNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Previous.
        /// </summary>
        public static string ColumnMenu_ReorderPrevious {
            get {
                return ResourceManager.GetString("ColumnMenu_ReorderPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ColumnMenu_Reset {
            get {
                return ResourceManager.GetString("ColumnMenu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set column position.
        /// </summary>
        public static string ColumnMenu_SetColumnPosition {
            get {
                return ResourceManager.GetString("ColumnMenu_SetColumnPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string ColumnMenu_SortAscending {
            get {
                return ResourceManager.GetString("ColumnMenu_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string ColumnMenu_SortDescending {
            get {
                return ResourceManager.GetString("ColumnMenu_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup column.
        /// </summary>
        public static string ColumnMenu_UngroupColumn {
            get {
                return ResourceManager.GetString("ColumnMenu_UngroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string ColumnMenu_Unlock {
            get {
                return ResourceManager.GetString("ColumnMenu_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ComboBox_Clear {
            get {
                return ResourceManager.GetString("ComboBox_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string ComboBox_NoData {
            get {
                return ResourceManager.GetString("ComboBox_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date format is not parsable. Please enter valid date..
        /// </summary>
        public static string DateInput_ParsingErrorMessage {
            get {
                return ResourceManager.GetString("DateInput_ParsingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is not valid..
        /// </summary>
        public static string DateInput_ValidationErrorMessage {
            get {
                return ResourceManager.GetString("DateInput_ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string DateRangePicker_End {
            get {
                return ResourceManager.GetString("DateRangePicker_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string DateRangePicker_Start {
            get {
                return ResourceManager.GetString("DateRangePicker_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DateTimePicker_Cancel {
            get {
                return ResourceManager.GetString("DateTimePicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTimePicker_Date {
            get {
                return ResourceManager.GetString("DateTimePicker_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string DateTimePicker_Set {
            get {
                return ResourceManager.GetString("DateTimePicker_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DateTimePicker_Time {
            get {
                return ResourceManager.GetString("DateTimePicker_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string DropDownList_NoData {
            get {
                return ResourceManager.GetString("DropDownList_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column on the left.
        /// </summary>
        public static string Editor_AddColumnLeft {
            get {
                return ResourceManager.GetString("Editor_AddColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column on the right.
        /// </summary>
        public static string Editor_AddColumnRight {
            get {
                return ResourceManager.GetString("Editor_AddColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row above.
        /// </summary>
        public static string Editor_AddRowAbove {
            get {
                return ResourceManager.GetString("Editor_AddRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row below.
        /// </summary>
        public static string Editor_AddRowBelow {
            get {
                return ResourceManager.GetString("Editor_AddRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center text.
        /// </summary>
        public static string Editor_AlignCenter {
            get {
                return ResourceManager.GetString("Editor_AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string Editor_AlignJustify {
            get {
                return ResourceManager.GetString("Editor_AlignJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text left.
        /// </summary>
        public static string Editor_AlignLeft {
            get {
                return ResourceManager.GetString("Editor_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text right.
        /// </summary>
        public static string Editor_AlignRight {
            get {
                return ResourceManager.GetString("Editor_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Editor_BackColor {
            get {
                return ResourceManager.GetString("Editor_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Editor_Bold {
            get {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert hyperlink.
        /// </summary>
        public static string Editor_CreateLink {
            get {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table.
        /// </summary>
        public static string Editor_CreateTable {
            get {
                return ResourceManager.GetString("Editor_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete column.
        /// </summary>
        public static string Editor_DeleteColumn {
            get {
                return ResourceManager.GetString("Editor_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        public static string Editor_DeleteRow {
            get {
                return ResourceManager.GetString("Editor_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Editor_DialogCancel {
            get {
                return ResourceManager.GetString("Editor_DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Editor_DialogInsert {
            get {
                return ResourceManager.GetString("Editor_DialogInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Editor_DialogUpdate {
            get {
                return ResourceManager.GetString("Editor_DialogUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        public static string Editor_FontFamily {
            get {
                return ResourceManager.GetString("Editor_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string Editor_FontSize {
            get {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Editor_ForeColor {
            get {
                return ResourceManager.GetString("Editor_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Editor_Format {
            get {
                return ResourceManager.GetString("Editor_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate text:.
        /// </summary>
        public static string Editor_ImageAltText {
            get {
                return ResourceManager.GetString("Editor_ImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string Editor_ImageHeight {
            get {
                return ResourceManager.GetString("Editor_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web address:.
        /// </summary>
        public static string Editor_ImageWebAddress {
            get {
                return ResourceManager.GetString("Editor_ImageWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string Editor_ImageWidth {
            get {
                return ResourceManager.GetString("Editor_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string Editor_Indent {
            get {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert file.
        /// </summary>
        public static string Editor_InsertFile {
            get {
                return ResourceManager.GetString("Editor_InsertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert HTML.
        /// </summary>
        public static string Editor_InsertHtml {
            get {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string Editor_InsertImage {
            get {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert ordered list.
        /// </summary>
        public static string Editor_InsertOrderedList {
            get {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert unordered list.
        /// </summary>
        public static string Editor_InsertUnorderedList {
            get {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Editor_Italic {
            get {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        public static string Editor_LinkOpenNewWindow {
            get {
                return ResourceManager.GetString("Editor_LinkOpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Editor_LinkText {
            get {
                return ResourceManager.GetString("Editor_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Editor_LinkTitle {
            get {
                return ResourceManager.GetString("Editor_LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web address:.
        /// </summary>
        public static string Editor_LinkWebAddress {
            get {
                return ResourceManager.GetString("Editor_LinkWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        public static string Editor_Outdent {
            get {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Editor_Redo {
            get {
                return ResourceManager.GetString("Editor_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string Editor_Strikethrough {
            get {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string Editor_Subscript {
            get {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string Editor_Superscript {
            get {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Editor_Underline {
            get {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Editor_Undo {
            get {
                return ResourceManager.GetString("Editor_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove hyperlink.
        /// </summary>
        public static string Editor_Unlink {
            get {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View HTML.
        /// </summary>
        public static string Editor_ViewHtml {
            get {
                return ResourceManager.GetString("Editor_ViewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Filter_Cancel {
            get {
                return ResourceManager.GetString("Filter_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is after.
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is after or equal to.
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is before.
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is before or equal to.
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_DateIsNotNull {
            get {
                return ResourceManager.GetString("Filter_DateIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_DateIsNull {
            get {
                return ResourceManager.GetString("Filter_DateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_EnumIsNotNull {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_EnumIsNull {
            get {
                return ResourceManager.GetString("Filter_EnumIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is false.
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is true.
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string Filter_NoData {
            get {
                return ResourceManager.GetString("Filter_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_NumberIsNotNull {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_NumberIsNull {
            get {
                return ResourceManager.GetString("Filter_NumberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Filter_Search {
            get {
                return ResourceManager.GetString("Filter_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Filter_SelectAll {
            get {
                return ResourceManager.GetString("Filter_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select value-.
        /// </summary>
        public static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty.
        /// </summary>
        public static string Filter_StringIsEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not empty.
        /// </summary>
        public static string Filter_StringIsNotEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_StringIsNotNull {
            get {
                return ResourceManager.GetString("Filter_StringIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has value.
        /// </summary>
        public static string Filter_StringIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_StringIsNull {
            get {
                return ResourceManager.GetString("Filter_StringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no value.
        /// </summary>
        public static string Filter_StringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Form_Clear {
            get {
                return ResourceManager.GetString("Form_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_CancelDelete {
            get {
                return ResourceManager.GetString("Grid_CancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records available..
        /// </summary>
        public static string Grid_NoRecords {
            get {
                return ResourceManager.GetString("Grid_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Grid_Search {
            get {
                return ResourceManager.GetString("Grid_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted in ascending order.
        /// </summary>
        public static string Grid_SortedAscending {
            get {
                return ResourceManager.GetString("Grid_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted in descending order.
        /// </summary>
        public static string Grid_SortedDescending {
            get {
                return ResourceManager.GetString("Grid_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string MultiSelect_Clear {
            get {
                return ResourceManager.GetString("MultiSelect_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string MultiSelect_NoData {
            get {
                return ResourceManager.GetString("MultiSelect_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease value.
        /// </summary>
        public static string NumericTextBox_DecreaseValue {
            get {
                return ResourceManager.GetString("NumericTextBox_DecreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase value.
        /// </summary>
        public static string NumericTextBox_IncreaseValue {
            get {
                return ResourceManager.GetString("NumericTextBox_IncreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} of {2} items.
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the first page.
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items per page.
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the last page.
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More pages.
        /// </summary>
        public static string Pager_MorePages {
            get {
                return ResourceManager.GetString("Pager_MorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next page.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Pager_PageDisplay {
            get {
                return ResourceManager.GetString("Pager_PageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous page.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all day.
        /// </summary>
        public static string Scheduler_AllDay {
            get {
                return ResourceManager.GetString("Scheduler_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Scheduler_Cancel {
            get {
                return ResourceManager.GetString("Scheduler_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Scheduler_Day {
            get {
                return ResourceManager.GetString("Scheduler_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Scheduler_Delete {
            get {
                return ResourceManager.GetString("Scheduler_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Scheduler_Editor_Description {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Scheduler_Editor_EditorTitle {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Scheduler_Editor_End {
            get {
                return ResourceManager.GetString("Scheduler_Editor_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time is required..
        /// </summary>
        public static string Scheduler_Editor_EndTimeRequiredValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EndTimeRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be after the Start time..
        /// </summary>
        public static string Scheduler_Editor_EndTimeValueValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EndTimeValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Day Event.
        /// </summary>
        public static string Scheduler_Editor_IsAllDay {
            get {
                return ResourceManager.GetString("Scheduler_Editor_IsAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Scheduler_Editor_Repeat {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Scheduler_Editor_Start {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is required..
        /// </summary>
        public static string Scheduler_Editor_StartTimeRequiredValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_StartTimeRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be before End time..
        /// </summary>
        public static string Scheduler_Editor_StartTimeValueValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_StartTimeValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Scheduler_Editor_Title {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string Scheduler_Editor_TitleRequiredValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_TitleRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Scheduler_Month {
            get {
                return ResourceManager.GetString("Scheduler_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDay.
        /// </summary>
        public static string Scheduler_MultiDay {
            get {
                return ResourceManager.GetString("Scheduler_MultiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Scheduler_Next {
            get {
                return ResourceManager.GetString("Scheduler_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Scheduler_Previous {
            get {
                return ResourceManager.GetString("Scheduler_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete only this event occurrence or the whole series?.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current occurrence.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the series.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recurring Appointment.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_After {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Label {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  occurrence(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Occurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_On {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Daily {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Monthly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Weekly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Yearly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_First {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Fourth {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Last {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Second {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Third {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekday.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Weekday {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekend day.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Weekend {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Of {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit only this event occurrence or the whole series?.
        /// </summary>
        public static string Scheduler_Recurrence_EditRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current occurrence.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the series.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Recurring Appointment.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Scheduler_Save {
            get {
                return ResourceManager.GetString("Scheduler_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full day.
        /// </summary>
        public static string Scheduler_ShowFullDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowFullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show business hours.
        /// </summary>
        public static string Scheduler_ShowWorkDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Scheduler_Today {
            get {
                return ResourceManager.GetString("Scheduler_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Scheduler_Week {
            get {
                return ResourceManager.GetString("Scheduler_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string Slider_Decrease {
            get {
                return ResourceManager.GetString("Slider_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string Slider_Increase {
            get {
                return ResourceManager.GetString("Slider_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Switch_OffLabel {
            get {
                return ResourceManager.GetString("Switch_OffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Switch_OnLabel {
            get {
                return ResourceManager.GetString("Switch_OnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TimePicker_Cancel {
            get {
                return ResourceManager.GetString("TimePicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string TimePicker_Day {
            get {
                return ResourceManager.GetString("TimePicker_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM/PM.
        /// </summary>
        public static string TimePicker_DayPeriod {
            get {
                return ResourceManager.GetString("TimePicker_DayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Era.
        /// </summary>
        public static string TimePicker_Era {
            get {
                return ResourceManager.GetString("TimePicker_Era", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string TimePicker_Hour {
            get {
                return ResourceManager.GetString("TimePicker_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string TimePicker_Minute {
            get {
                return ResourceManager.GetString("TimePicker_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string TimePicker_Month {
            get {
                return ResourceManager.GetString("TimePicker_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string TimePicker_Now {
            get {
                return ResourceManager.GetString("TimePicker_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string TimePicker_Quarter {
            get {
                return ResourceManager.GetString("TimePicker_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string TimePicker_Second {
            get {
                return ResourceManager.GetString("TimePicker_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string TimePicker_Set {
            get {
                return ResourceManager.GetString("TimePicker_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle clock.
        /// </summary>
        public static string TimePicker_ToggleClock {
            get {
                return ResourceManager.GetString("TimePicker_ToggleClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string TimePicker_WeekDay {
            get {
                return ResourceManager.GetString("TimePicker_WeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TimePicker_Year {
            get {
                return ResourceManager.GetString("TimePicker_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string TimePicker_Zone {
            get {
                return ResourceManager.GetString("TimePicker_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TreeList_Cancel {
            get {
                return ResourceManager.GetString("TreeList_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        public static string TreeList_Create {
            get {
                return ResourceManager.GetString("TreeList_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TreeList_Delete {
            get {
                return ResourceManager.GetString("TreeList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TreeList_Edit {
            get {
                return ResourceManager.GetString("TreeList_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string TreeList_Search {
            get {
                return ResourceManager.GetString("TreeList_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted in ascending order.
        /// </summary>
        public static string TreeList_SortedAscending {
            get {
                return ResourceManager.GetString("TreeList_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted in descending order.
        /// </summary>
        public static string TreeList_SortedDescending {
            get {
                return ResourceManager.GetString("TreeList_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TreeList_Update {
            get {
                return ResourceManager.GetString("TreeList_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Upload_Clear {
            get {
                return ResourceManager.GetString("Upload_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File failed to upload..
        /// </summary>
        public static string Upload_FileStatusFailed {
            get {
                return ResourceManager.GetString("Upload_FileStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully uploaded..
        /// </summary>
        public static string Upload_FileStatusUploaded {
            get {
                return ResourceManager.GetString("Upload_FileStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Upload_HeaderStatusUploaded {
            get {
                return ResourceManager.GetString("Upload_HeaderStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Upload_HeaderStatusUploading {
            get {
                return ResourceManager.GetString("Upload_HeaderStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type not allowed..
        /// </summary>
        public static string Upload_InvalidFileExtension {
            get {
                return ResourceManager.GetString("Upload_InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size too large..
        /// </summary>
        public static string Upload_InvalidMaxFileSize {
            get {
                return ResourceManager.GetString("Upload_InvalidMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size too small..
        /// </summary>
        public static string Upload_InvalidMinFileSize {
            get {
                return ResourceManager.GetString("Upload_InvalidMinFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files....
        /// </summary>
        public static string Upload_SelectFiles {
            get {
                return ResourceManager.GetString("Upload_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload_UploadFiles {
            get {
                return ResourceManager.GetString("Upload_UploadFiles", resourceCulture);
            }
        }
    }
}
