<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.*" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.*" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="10.*" />
        <PackageReference Include="Telerik.UI.for.Blazor" Version="14.1.0" />
        <PackageReference Include="Telerik.Licensing" Version="*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\LazyLoadTelerikComponents.Shared.csproj" />
    </ItemGroup>

    <!-- Define the Telerik assemblies and dependencies that will be lazy loaded -->
    <ItemGroup>
        <!-- Components and data binding -->
        <BlazorWebAssemblyLazyLoad Include="Telerik.Blazor.wasm" />
        <BlazorWebAssemblyLazyLoad Include="Telerik.DataSource.wasm" />
        <BlazorWebAssemblyLazyLoad Include="System.Data.Common.wasm" />
        <BlazorWebAssemblyLazyLoad Include="System.Linq.Queryable.wasm" />
        <!-- Icons -->
        <BlazorWebAssemblyLazyLoad Include="Telerik.SvgIcons.wasm" />
        <BlazorWebAssemblyLazyLoad Include="Telerik.FontIcons.wasm" />
        <!-- PivotGrid -->
        <BlazorWebAssemblyLazyLoad Include="Telerik.Pivot.Core.wasm" />
        <BlazorWebAssemblyLazyLoad Include="Telerik.Pivot.DataProviders.Xmla.wasm" />
        <!-- Scheduler -->
        <BlazorWebAssemblyLazyLoad Include="Telerik.Recurrence.wasm" />
        <!-- Excel export -->
        <BlazorWebAssemblyLazyLoad Include="Telerik.Documents.SpreadsheetStreaming.wasm" />
        <BlazorWebAssemblyLazyLoad Include="Telerik.Zip.wasm" />
        <!-- PDF export (only for version 8.0.0 and above) -->
        <BlazorWebAssemblyLazyLoad Include="Telerik.Documents.Spreadsheet.FormatProviders.Pdf.wasm" />
    </ItemGroup>
</Project>