//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerLocalizationResx.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelerikMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelerikMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerLocalizationResx.Resources.TelerikMessages", typeof(TelerikMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Calendar_Today {
            get {
                return ResourceManager.GetString("Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ComboBox_Clear {
            get {
                return ResourceManager.GetString("ComboBox_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string ComboBox_NoData {
            get {
                return ResourceManager.GetString("ComboBox_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DateTimePicker_Cancel {
            get {
                return ResourceManager.GetString("DateTimePicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTimePicker_Date {
            get {
                return ResourceManager.GetString("DateTimePicker_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string DateTimePicker_Set {
            get {
                return ResourceManager.GetString("DateTimePicker_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DateTimePicker_Time {
            get {
                return ResourceManager.GetString("DateTimePicker_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string DropDownList_NoData {
            get {
                return ResourceManager.GetString("DropDownList_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional operator.
        /// </summary>
        public static string Filter_AdditionalOperator {
            get {
                return ResourceManager.GetString("Filter_AdditionalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional value.
        /// </summary>
        public static string Filter_AdditionalValue {
            get {
                return ResourceManager.GetString("Filter_AdditionalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Filter_Cancel {
            get {
                return ResourceManager.GetString("Filter_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is after.
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is after or equal to.
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is before.
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is before or equal to.
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_DateIsNotNull {
            get {
                return ResourceManager.GetString("Filter_DateIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_DateIsNull {
            get {
                return ResourceManager.GetString("Filter_DateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_EnumIsNotNull {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_EnumIsNull {
            get {
                return ResourceManager.GetString("Filter_EnumIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show items with value that:.
        /// </summary>
        public static string Filter_Info {
            get {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is false.
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is true.
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters logic.
        /// </summary>
        public static string Filter_Logic {
            get {
                return ResourceManager.GetString("Filter_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_NumberIsNotNull {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_NumberIsNull {
            get {
                return ResourceManager.GetString("Filter_NumberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Filter_Operator {
            get {
                return ResourceManager.GetString("Filter_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Filter_Search {
            get {
                return ResourceManager.GetString("Filter_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected items.
        /// </summary>
        public static string Filter_SelectedItemsFormat {
            get {
                return ResourceManager.GetString("Filter_SelectedItemsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select value-.
        /// </summary>
        public static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty.
        /// </summary>
        public static string Filter_StringIsEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not empty.
        /// </summary>
        public static string Filter_StringIsNotEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string Filter_StringIsNotNull {
            get {
                return ResourceManager.GetString("Filter_StringIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has value.
        /// </summary>
        public static string Filter_StringIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string Filter_StringIsNull {
            get {
                return ResourceManager.GetString("Filter_StringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no value.
        /// </summary>
        public static string Filter_StringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show items with value that:.
        /// </summary>
        public static string Filter_Title {
            get {
                return ResourceManager.GetString("Filter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Filter_Value {
            get {
                return ResourceManager.GetString("Filter_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        public static string Grid_CancelChanges {
            get {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_CancelDelete {
            get {
                return ResourceManager.GetString("Grid_CancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Grid_CheckAll {
            get {
                return ResourceManager.GetString("Grid_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Settings.
        /// </summary>
        public static string Grid_ColumnSettings {
            get {
                return ResourceManager.GetString("Grid_ColumnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string Grid_Confirmation {
            get {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Grid_ConfirmDelete {
            get {
                return ResourceManager.GetString("Grid_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Grid_Done {
            get {
                return ResourceManager.GetString("Grid_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string Grid_Excel {
            get {
                return ResourceManager.GetString("Grid_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Grid_Lock {
            get {
                return ResourceManager.GetString("Grid_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string Grid_Pdf {
            get {
                return ResourceManager.GetString("Grid_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Grid_SaveChanges {
            get {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Grid_Search {
            get {
                return ResourceManager.GetString("Grid_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Grid_Unlock {
            get {
                return ResourceManager.GetString("Grid_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can drag a column header and drop it here to group by that column.
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease value.
        /// </summary>
        public static string NumericTextBox_DecreaseValue {
            get {
                return ResourceManager.GetString("NumericTextBox_DecreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase value.
        /// </summary>
        public static string NumericTextBox_IncreaseValue {
            get {
                return ResourceManager.GetString("NumericTextBox_IncreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} of {2} items.
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the first page.
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items per page.
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the last page.
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More pages.
        /// </summary>
        public static string Pager_MorePages {
            get {
                return ResourceManager.GetString("Pager_MorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next page.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous page.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TimePicker_Cancel {
            get {
                return ResourceManager.GetString("TimePicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string TimePicker_Day {
            get {
                return ResourceManager.GetString("TimePicker_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM/PM.
        /// </summary>
        public static string TimePicker_DayPeriod {
            get {
                return ResourceManager.GetString("TimePicker_DayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Era.
        /// </summary>
        public static string TimePicker_Era {
            get {
                return ResourceManager.GetString("TimePicker_Era", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string TimePicker_Hour {
            get {
                return ResourceManager.GetString("TimePicker_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string TimePicker_Minute {
            get {
                return ResourceManager.GetString("TimePicker_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string TimePicker_Month {
            get {
                return ResourceManager.GetString("TimePicker_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string TimePicker_Now {
            get {
                return ResourceManager.GetString("TimePicker_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string TimePicker_Quarter {
            get {
                return ResourceManager.GetString("TimePicker_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string TimePicker_Second {
            get {
                return ResourceManager.GetString("TimePicker_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string TimePicker_Set {
            get {
                return ResourceManager.GetString("TimePicker_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle clock.
        /// </summary>
        public static string TimePicker_ToggleClock {
            get {
                return ResourceManager.GetString("TimePicker_ToggleClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string TimePicker_WeekDay {
            get {
                return ResourceManager.GetString("TimePicker_WeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TimePicker_Year {
            get {
                return ResourceManager.GetString("TimePicker_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string TimePicker_Zone {
            get {
                return ResourceManager.GetString("TimePicker_Zone", resourceCulture);
            }
        }
    }
}
